"""empty message

Revision ID: 92d260834de
Revises: None
Create Date: 2014-07-13 13:46:53.505094

"""
from geo import app

# revision identifiers, used by Alembic.
revision = '92d260834de'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_number', sa.String(length=9), nullable=False),
    sa.Column('extent', ga.Geometry('MULTIPOLYGON', srid=app.config['SPATIAL_REFERENCE_SYSTEM_IDENTIFIER']), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_number')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titles')
    ### end Alembic commands ###
